Test bulk creator
laws-africa/indigo pull request #1203
Opened 2020-11-09 17:18 UTC by goose-life

2020-11-10 07:14 UTC, longhotsummer commented on indigo/tests/bulk_creator/test_bulk_creator.py
> +        creator = plugins.for_locale('bulk-creator', 'za', None, None)
Rather create the instance explicitly from the class, so it's clear what's being tested.

2020-11-10 07:15 UTC, longhotsummer commented on indigo/tests/bulk_creator/test_bulk_creator.py
> +        creator = plugins.for_locale('bulk-creator', 'za', None, None)
If the ZA version is being tested, these tests should be in the tests module for indigo_za (ie. in the same project).

2020-11-10 07:16 UTC, longhotsummer requested changes
Nice tests. Please change the test to be explicit about the class that is being tested, and if that must be the ZA importer, then move the tests to be in the same project.

2020-11-10 16:04 UTC, goose-life commented
Basic:
![image](https://user-images.githubusercontent.com/32566441/98698204-732b4880-237e-11eb-970d-ad6c1823b469.png)
![image](https://user-images.githubusercontent.com/32566441/98698630-ee8cfa00-237e-11eb-9eb3-05826fa7b71d.png)

2020-11-10 16:05 UTC, goose-life commented
Errors:
![image](https://user-images.githubusercontent.com/32566441/98698840-285e0080-237f-11eb-96c2-a757c90e2818.png)
![image](https://user-images.githubusercontent.com/32566441/98698916-3d3a9400-237f-11eb-9f9a-b7df742219ab.png)

2020-11-10 16:08 UTC, goose-life commented
Commencements:
![image](https://user-images.githubusercontent.com/32566441/98699197-8db1f180-237f-11eb-8b0c-4ef6ea49dd3e.png)
![image](https://user-images.githubusercontent.com/32566441/98699317-ae7a4700-237f-11eb-9e5e-db6e7b8332cc.png)

2020-11-10 16:22 UTC, goose-life commented
Amendments:
![image](https://user-images.githubusercontent.com/32566441/98700371-ca321d00-2380-11eb-98ad-26e8795b6740.png)
![image](https://user-images.githubusercontent.com/32566441/98700471-e33ace00-2380-11eb-8fcf-4628420e0589.png)

![image](https://user-images.githubusercontent.com/32566441/98700850-517f9080-2381-11eb-897c-38920837bbfe.png)
![image](https://user-images.githubusercontent.com/32566441/98700900-5fcdac80-2381-11eb-937f-f4f672205569.png)

2020-11-10 16:25 UTC, goose-life commented
Repeals:
![image](https://user-images.githubusercontent.com/32566441/98701526-0d40c000-2382-11eb-9112-10933a18b428.png)
![image](https://user-images.githubusercontent.com/32566441/98701636-29dcf800-2382-11eb-9e9d-d831d25c0f50.png)

2020-11-10 16:28 UTC, goose-life commented
Parents:
![image](https://user-images.githubusercontent.com/32566441/98701890-70caed80-2382-11eb-99f5-bd92b0c9a1bd.png)
![image](https://user-images.githubusercontent.com/32566441/98701951-83452700-2382-11eb-8692-8d5bc6ae9511.png)

2020-11-10 16:32 UTC, goose-life commented
Duplicates:
![image](https://user-images.githubusercontent.com/32566441/98702382-f64e9d80-2382-11eb-8611-f1b1aea8350d.png)
![image](https://user-images.githubusercontent.com/32566441/98702425-06ff1380-2383-11eb-8ba6-37b90f962c5c.png)

2020-11-11 06:56 UTC, longhotsummer commented on indigo_app/templates/indigo_api/work_new_batch.html
> +              <th>Notes (shown in Preview only)</th>
Minor: I don't think anyone's going to be confused if this is just shown in preview, but not after import. So perhaps the heading can just be "Notes"/"Comments"/"Import notes".

2020-11-11 06:56 UTC, longhotsummer approved these changes

2020-11-11 07:12 UTC, goose-life commented on indigo_app/templates/indigo_api/work_new_batch.html
> +              <th>Notes (shown in Preview only)</th>
```suggestion
              <th>Notes</th>
```

2020-11-11 07:15 UTC, longhotsummer approved these changes

2020-11-11 07:19 UTC, merged