Per-place setting for 'no publication document' text
laws-africa/indigo pull request #1235
Opened 2021-01-20 11:02 UTC by goose-life

closes #1233 

TODO: will `blocktrans` work here or always display the saved string?

Form:
![image](https://user-images.githubusercontent.com/32566441/105165812-792c6b00-5b1f-11eb-9523-4ea76c9bdd76.png)

Coverpage English:
![image](https://user-images.githubusercontent.com/32566441/105165891-9103ef00-5b1f-11eb-8965-7e0f46e51443.png)

Coverpage Sotho:
![image](https://user-images.githubusercontent.com/32566441/105165925-9a8d5700-5b1f-11eb-8619-81ebfd0f7193.png)

2021-01-20 11:26 UTC, longhotsummer commented on indigo_api/templates/indigo_api/akn/coverpage_act.html
> +              [{% blocktrans with no_publication_document_text=document.work.place.settings.no_publication_document_text %}{{ no_publication_document_text }}{% endblocktrans %}]
I don't think blocktrans is quite right, see here: https://stackoverflow.com/questions/6546933/django-translate-variable-content-in-template. We want it to translate the contents of the variable, not treat it as a translatable string containing a variable.

We should also check if there is no message and not include this notice at all - ie. provide a way to turn it off.

2021-01-20 11:29 UTC, longhotsummer commented on indigo_api/models/places.py
> +    no_publication_document_text = models.CharField(max_length=1024, default='Note: The original publication document is not available and this content could not be verified.')
`null=False, blank=True` ? So we always want a string, but it can be blank.

2021-01-20 13:05 UTC, goose-life commented
Coverpage Sotho, after adding the following to st/LC_MESSAGES/django.po:
```
msgid "Note: The original publication document is not available and this content could not be verified."
msgstr "S Sotho translation"
```

![image](https://user-images.githubusercontent.com/32566441/105178558-d8df4200-5b30-11eb-9a79-c05c9fd61921.png)

2021-01-22 07:34 UTC, longhotsummer approved these changes

2021-01-22 07:43 UTC, longhotsummer requested changes
One more thing: in order for Django to realise that that string is translatable (and therefore present it for translation in CrowdIn), we need to mark it as translatable and [run makemessages](https://github.com/laws-africa/indigo#adding-translation-strings).

See details at https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#lazy-translation.

Basically, import `ugettext_lazy` as `_` and apply it to the default string in the model definition `_('Note: blah blah')`.

Then run makemessages as documented in Indigo's readme and check that it shows up.

2021-01-22 09:52 UTC, longhotsummer approved these changes

2021-01-22 11:54 UTC, merged