replace-c-style-format-with-f-strings
laws-africa/indigo pull request #1799
Opened 2023-07-27 07:43 UTC by nicksonlangat

2023-09-11 09:48 UTC, longhotsummer commented on indigo/bulk_creator.py
> -                    work = _('%s (about to be imported)') % given_string
this has to remain as-is, because the interpolation has to happen after the translation (the `_(...)`).

2023-09-11 09:50 UTC, longhotsummer requested changes
Hi @nicksonlangat thanks for this, and sorry for the delay. It looks good, just the one with the translation which should be undone.

2023-09-11 18:12 UTC, nicksonlangat commented
> Hi @nicksonlangat thanks for this, and sorry for the delay. It looks good, just the one with the translation which should be undone.

Updated pr

2023-09-12 06:55 UTC, longhotsummer commented
Thanks. Holding off until https://github.com/laws-africa/indigo/pull/1827 is merged which should fix the tests.

2023-09-14 09:24 UTC, longhotsummer commented
@nicksonlangat pls merge master into your branch, that should fix the tests.

2023-09-15 11:25 UTC, nicksonlangat commented
> @nicksonlangat pls merge master into your branch, that should fix the tests.

Done

2024-08-14 14:04 UTC, closed without merging

2024-08-14 14:04 UTC, longhotsummer commented
I'm closing because this is no so out of date :(